version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: ./.build/prod/Dockerfile
    environment:
      - VIRTUAL_HOST=consulta-pro.imoveispro.com.br
      - VIRTUAL_PORT=3000
    restart: always
    ports:
      - 8088:3000

networks:
  default:
    external:
      name: nginx-proxy